setup viaduct, provide basic version
kubeedge/viaduct pull request #1
Opened 2019-03-25 08:18 UTC by glenn-lg

setup viaduct, provide basic version

2019-03-25 08:58 UTC, sids-b requested changes
Please use dep to manage vendor so that we don't have test files/unwanted packages in vendor.
Please refer https://github.com/golang/dep

2019-03-25 08:58 UTC, sids-b commented on examples/chat/ca.crt
> +-----BEGIN CERTIFICATE-----
Can we add steps to generate certificates in the readme of examples/chat ??

2019-03-25 08:58 UTC, sids-b commented on examples/chat/server.go
> +	"github.com/kubeedge/viaduct/pkg/api"
please place this package with the batch of vendor package.

2019-03-25 09:03 UTC, sids-b commented
cc @qizha for review

2019-03-25 09:45 UTC, sids-b commented
@glenn-lg , can you please seperate out the commits. 1 for vendor and 1 for source code ?

2019-03-26 04:16 UTC, sids-b approved these changes
LGTM

2019-03-26 04:17 UTC, sids-b commented
cc @qizha for review and merging

2019-03-26 06:05 UTC, qizha commented
LGTM

2019-03-26 06:05 UTC, merged