Adding Unit Tests
kubeedge/viaduct pull request #6
Opened 2019-03-30 14:33 UTC by lidiyag

This PR adds unit tests for kubeedge/viaduct along with the required mocks

2019-03-30 16:35 UTC, sids-b requested changes
Please gofmt all files.

2019-03-30 16:35 UTC, sids-b commented on pkg/conn/factory_test.go
> +}
Please add blank line at the end

2019-03-30 16:35 UTC, sids-b commented on pkg/conn/factory_test.go
> +	"reflect"
seperate golang, kubeedge and vendor packages

2019-03-30 16:35 UTC, sids-b commented on pkg/lane/lane_test.go
> +	"reflect"
seperate golang, kubeedge and vendor packages

2019-03-30 16:35 UTC, sids-b commented on pkg/lane/quic_test.go
> +	"github.com/kubeedge/beehive/pkg/core/model"
seperate golang, kubeedge and vendor packages

2019-03-30 16:35 UTC, sids-b commented on pkg/lane/quic_test.go
> +
remove extra blank line

2019-03-30 16:35 UTC, sids-b commented on pkg/lane/quic_test.go
> +			if ( tt.name == "Test-FailureCase") {
the main idea of table driven tests is easy addition of test. We have if else condition based on name of the test which should be unique for all tests, if we want to add 3rd we may require another else if. Please refactor.

2019-03-30 16:35 UTC, sids-b commented on pkg/lane/quic_test.go
> +func TestQuicLane_ReadMessage(t *testing.T) {
camel case please.
Applicable to similar cases below

2019-03-30 16:35 UTC, sids-b commented on pkg/lane/quic_test.go
> +func TestQuicLane_WriteMessage(t *testing.T) {
camel case please

2019-03-30 16:35 UTC, sids-b commented on pkg/packer/reader_test.go
> +	"github.com/kubeedge/viaduct/pkg/translator"
seperate golang, kubeedge and vendor packages

2019-03-30 16:35 UTC, sids-b commented on pkg/lane/quic_test.go
> +			name:"Test1",
Please give a name that desribes the test in short.
Applicable to similar places.

2019-03-30 16:35 UTC, sids-b commented on pkg/packer/reader_test.go
> +	err1:=errors.New("Error")
Lets not suffix names with numbers. Please change it to something that says why this error is used.

2019-04-05 09:33 UTC, sids-b commented on mocks/cover.out
> +mode: set
Why is this file used ??

2019-04-05 10:12 UTC, lidiyag commented on mocks/cover.out
> +mode: set
Pushed by mistake...Updated.

2019-04-05 16:33 UTC, sids-b approved these changes
LGTM

2019-04-05 16:35 UTC, merged